---
- name: Install Database Server
  tags: setup_database
  hosts: database
  become: yes
  become_user: root
  gather_facts: true
  roles:
  - mysql_server

- name: Install Tomcat Server
  tags: setup_tomcat
  hosts: webserver
  become: yes
  become_user: root
  gather_facts: true
  roles:
  - tomcat_server
  - supercars_app